CLIENT_ID_GOOGLE_AUTH=
KTOR_ENTRY_URL_ANDROID=
KTOR_ENTRY_URL_IOS=
IOS_CLIENT_ID=
IOS_REVERSE_CLIENT_ID=
GO_PORT=
GO_VALKEY_ADDR=
GO_PG_HOST=
GO_PG_USERNAME=
GO_PG_DATABASE=
GO_PG_PASSWORD=
GO_PG_PORT=